jobs:
  include:
    - stage: generator
      language: java
      install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script:
    - cd NetflixRouletteGenerator
        - mvn org.eclipse.acceleo:org.eclipse.acceleo.maven:acceleo-compile deploy
    - stage: uml	
      language: java
      script:
    - cd ..
        - cd NetflixRouletteUML
        - "mvn org.eclipse.acceleo:org.eclipse.acceleo.maven.launcher:acceleo-launcher"
    - stage: build backend
      install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script:
        - mvn deploy
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: netflixroulette
        api_key: $HEROKU_API_KEY
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: netflixroulette

