$HOME/.m2/settings.xmllanguage: java


jobs:
  include:
    - stage: Build generator
      language: java
      install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script:
        - cd NetflixRouletteGenerator
        - mvn org.eclipse.acceleo:org.eclipse.acceleo.maven:acceleo-compile deploy
    - stage: UML - generate backend
      language: java
      script:
        - cd NetflixRouletteUML
        - mvn org.eclipse.acceleo:org.eclipse.acceleo.maven.launcher:acceleo-launcher
    - stage: Build backend
      install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script:
        - cd NetflixRouletteBackend
        - mvn deploy
    - stage: Unit- and integration test for backend
      script:
        - cd NetflixRouletteBackend
        - mvn verify
    - stage: Static code analysis
      language: java
      addons:
        sonarcloud:
          organization: str7946-github
          token: $SONAR_TOKEN
      script:
        - cd NetflixRouletteBackend
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent javadoc:javadoc verify sonar:sonar
        - cd ..
        - git clone https://github.com/Kevinpetschulat/NetflixRouletteDocs.git
        - rm -rf NetflixRouletteDocs/generated/jacoco-ut NetflixRouletteDocs/generated/jacoco-it NetflixRouletteDocs/generated/apidocs
        - cp -r NetflixRouletteBackend/target/site/jacoco-ut NetflixRouletteDocs/generated/
        - cp -r NetflixRouletteBackend/target/site/jacoco-it NetflixRouletteDocs/generated/
        - cp -r NetflixRouletteBackend/target/site/apidocs NetflixRouletteDocs/generated/
        - cd NetflixRouletteDocs/generated
        - git add --all
        - git commit -am "update documentation"
        - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/Kevinpetschulat/NetflixRouletteDocs.git" master
    - stage: Deploy backend to staging
      script: skip
      before_deploy:
        - cd NetflixRouletteBackend
      deploy: &heroku
        provider: heroku
        app: netflixroulette-backend-stage
        api_key: $HEROKU_API_KEY
    - stage: Deploy frontend to staging
      script: skip
      before_deploy:
        - cd NetflixRouletteFrontend
      deploy:
        <<: *heroku
        app: netflixroulette-stage
    - stage: Deploy code docs
      script: skip
      before_deploy:
        - git clone https://github.com/Kevinpetschulat/NetflixRouletteDocs.git
        - cd NetflixRouletteDocs
      deploy: &heroku
        provider: heroku
        app: netflixroulette-docs
        api_key: $HEROKU_API_KEY
    - stage: Deploy backend to production
      script: skip
      before_deploy:
        - cd NetflixRouletteBackend
      deploy: &heroku
        provider: heroku
        app: netflixroulette-backend
        api_key: $HEROKU_API_KEY
    - stage: Deploy frontend to production
      script: skip
      before_deploy:
        - cd NetflixRouletteFrontend
      deploy:
        <<: *heroku
        app: netflixroulette
    - stage: Check production availability
      script:
        - 'curl https://netflixroulette.herokuapp.com/'
        - 'curl https://netflixroulette-docs.herokuapp.com/generated/index.html'
